### ISSUE TITLE
cppreference: Parse reference pages for non-symbols

### ISSUE THREAD

**Issue by jchristgit** [strinking/docflow#10]
There are several smaller pages that provide an overview over a smaller topic, for example the [Thread Support Library](http://en.cppreference.com/w/cpp/thread). The links in here should be extracted along with their descriptions.

**Comment by aeshthetic** [comment]
added with `stub_spider.py` and can be tested with `scrapy crawl stub -o stub.json`

**Comment by byronvanstien** [comment]
In future consider referencing the issues you fix in the PR and closing it on merge :+1:

**Comment by jchristgit** [comment]
Also consider using the labels we have :octocat:
