### ISSUE TITLE
cppreference: "Since C++ 1x" specifiers don't parse correctly

### ISSUE THREAD

**Issue by jchristgit** [strinking/docflow#12]
The extraction for signatures currently splits the scraped data on semicolons, resulting in specifiers for which standard something was introduced to be put inside the next signature or even an empty one.
```json
      "float \u00a0 \u00a0 \u00a0 acosh( float arg )",
      "(since C++11)double \u00a0 \u00a0 \u00a0acosh( double arg )",
      "(since C++11)long double acosh( long double arg )",
      "(since C++11)double \u00a0 \u00a0 \u00a0acosh( Integral arg )",
      "(since C++11)"
```
A possible solution would be writing a custom split function which would search for any occurrence of `(since ...` and split after it if it was found, or simply default to splitting on semicolons if no occurrence of the pattern was found.

**Comment by Volcyy** [comment]
Fixed in docsearch-cppreference.

**Comment by jchristgit** [comment]
This is fixed in `docsearch-cppreference` as the signatures are now simply written in a code block, allowing the reader to easily spot the standard support.

**Comment by aeshthetic** [comment]
can this be closed now?
